-- StreamHub: execute este arquivo no SQL Editor do Supabase.
-- Plataforma destinada exclusivamente à distribuição de conteúdo licenciado.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  phone text,
  role text not null default 'customer' check (role in ('customer','support','admin')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.plans (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text not null unique,
  description text,
  price_cents integer not null check (price_cents >= 0),
  duration_days integer not null default 30 check (duration_days >= 0),
  features jsonb not null default '[]'::jsonb,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.payments (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  plan_id uuid not null references public.plans(id),
  amount_cents integer not null check (amount_cents > 0),
  currency text not null default 'BRL',
  provider text not null,
  provider_transaction_id text,
  status text not null default 'pending' check (status in ('pending','processing','paid','approved','completed','confirmed','failed','cancelled','expired','refunded')),
  qr_code text,
  copy_paste text,
  expires_at timestamptz,
  provider_response jsonb,
  webhook_payload jsonb,
  paid_at timestamptz,
  created_at timestamptz not null default now()
);

-- Compatibilidade com projetos onde a tabela payments já existia sem esta coluna.
-- CREATE TABLE IF NOT EXISTS não adiciona colunas em tabelas antigas.
alter table public.payments add column if not exists paid_at timestamptz;

create unique index if not exists payments_provider_transaction_unique
  on public.payments(provider, provider_transaction_id)
  where provider_transaction_id is not null;
create index if not exists payments_user_created_idx on public.payments(user_id, created_at desc);
create index if not exists payments_status_paid_idx on public.payments(status, paid_at desc);

create table if not exists public.subscriptions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null unique references public.profiles(id) on delete cascade,
  plan_id uuid references public.plans(id),
  payment_id uuid references public.payments(id),
  status text not null default 'active' check (status in ('active','paused','cancelled','expired')),
  is_trial boolean not null default false,
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  updated_at timestamptz not null default now(),
  constraint subscriptions_valid_period check (ends_at > starts_at)
);
create index if not exists subscriptions_active_idx on public.subscriptions(status, ends_at desc);

create table if not exists public.access_tokens (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  subscription_id uuid references public.subscriptions(id) on delete cascade,
  token_hash text not null unique,
  kind text not null check (kind in ('trial','subscription')),
  created_at timestamptz not null default now(),
  last_used_at timestamptz,
  revoked_at timestamptz
);
alter table public.access_tokens add column if not exists last_used_at timestamptz;
create index if not exists access_tokens_user_idx on public.access_tokens(user_id, created_at desc);

create table if not exists public.trial_claims (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null unique references public.profiles(id) on delete cascade,
  email text,
  ip_hash text,
  claimed_at timestamptz not null default now()
);
create index if not exists trial_claims_ip_idx on public.trial_claims(ip_hash);

create table if not exists public.content_items (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  description text,
  category text,
  poster_url text,
  provider_asset_id text not null unique,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.usage_events (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete set null,
  event_type text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists usage_events_user_created_idx on public.usage_events(user_id, created_at desc);
create index if not exists usage_events_type_created_idx on public.usage_events(event_type, created_at desc);

create table if not exists public.support_tickets (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  subject text not null,
  message text not null,
  priority text not null default 'normal' check (priority in ('low','normal','high','urgent')),
  status text not null default 'open' check (status in ('open','in_progress','resolved','closed')),
  admin_reply text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists support_tickets_user_idx on public.support_tickets(user_id, created_at desc);
create index if not exists support_tickets_status_idx on public.support_tickets(status, created_at desc);

create table if not exists public.webhook_events (
  id bigint generated by default as identity primary key,
  provider text not null,
  event_hash text not null unique,
  payload jsonb not null,
  created_at timestamptz not null default now()
);


create or replace function public.claim_trial(
  p_user_id uuid,
  p_email text,
  p_ip_hash text,
  p_duration_minutes integer default 60
)
returns table(subscription_id uuid, trial_ends_at timestamptz)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_plan_id uuid;
  v_subscription_id uuid;
  v_ends_at timestamptz;
begin
  if exists (select 1 from public.trial_claims where user_id = p_user_id) then
    raise exception 'trial_already_used';
  end if;

  if exists (
    select 1 from public.subscriptions
    where user_id = p_user_id and status = 'active' and ends_at > now()
  ) then
    raise exception 'active_subscription';
  end if;

  select id into v_plan_id from public.plans where slug = 'teste-1h' limit 1;
  v_ends_at := now() + make_interval(mins => greatest(p_duration_minutes, 1));

  insert into public.trial_claims(user_id, email, ip_hash, claimed_at)
  values (p_user_id, p_email, p_ip_hash, now());

  insert into public.subscriptions(
    user_id, plan_id, payment_id, status, is_trial, starts_at, ends_at, updated_at
  ) values (
    p_user_id, v_plan_id, null, 'active', true, now(), v_ends_at, now()
  )
  on conflict (user_id) do update set
    plan_id = excluded.plan_id,
    payment_id = null,
    status = 'active',
    is_trial = true,
    starts_at = excluded.starts_at,
    ends_at = excluded.ends_at,
    updated_at = now()
  returning id into v_subscription_id;

  return query select v_subscription_id, v_ends_at;
end;
$$;

revoke all on function public.claim_trial(uuid, text, text, integer) from public, anon, authenticated;
grant execute on function public.claim_trial(uuid, text, text, integer) to service_role;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, full_name)
  values (new.id, coalesce(new.raw_user_meta_data->>'full_name', ''))
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();


create or replace function public.current_user_role()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select role from public.profiles where id = auth.uid();
$$;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin'
  );
$$;


insert into public.profiles (id, full_name, created_at, updated_at)
select id, coalesce(raw_user_meta_data->>'full_name', ''), created_at, now()
from auth.users
on conflict (id) do nothing;

alter table public.profiles enable row level security;
alter table public.plans enable row level security;
alter table public.payments enable row level security;
alter table public.subscriptions enable row level security;
alter table public.access_tokens enable row level security;
alter table public.trial_claims enable row level security;
alter table public.content_items enable row level security;
alter table public.usage_events enable row level security;
alter table public.support_tickets enable row level security;
alter table public.webhook_events enable row level security;

-- Remove políticas antigas com os mesmos nomes para permitir reexecução do arquivo.
drop policy if exists "profiles_select_own" on public.profiles;
drop policy if exists "profiles_update_own" on public.profiles;
drop policy if exists "plans_public_read" on public.plans;
drop policy if exists "payments_select_own" on public.payments;
drop policy if exists "subscriptions_select_own" on public.subscriptions;
drop policy if exists "support_select_own" on public.support_tickets;
drop policy if exists "support_insert_own" on public.support_tickets;
drop policy if exists "admin_profiles_all" on public.profiles;
drop policy if exists "admin_payments_all" on public.payments;
drop policy if exists "admin_subscriptions_all" on public.subscriptions;
drop policy if exists "admin_support_all" on public.support_tickets;
drop policy if exists "admin_usage_all" on public.usage_events;

create policy "profiles_select_own" on public.profiles
for select to authenticated using (id = auth.uid());

create policy "plans_public_read" on public.plans
for select to anon, authenticated using (active = true);

create policy "payments_select_own" on public.payments
for select to authenticated using (user_id = auth.uid());

create policy "subscriptions_select_own" on public.subscriptions
for select to authenticated using (user_id = auth.uid());

create policy "support_select_own" on public.support_tickets
for select to authenticated using (user_id = auth.uid());

create policy "support_insert_own" on public.support_tickets
for insert to authenticated with check (user_id = auth.uid());

create policy "admin_profiles_all" on public.profiles
for all to authenticated using (public.is_admin()) with check (public.is_admin());

create policy "admin_payments_all" on public.payments
for all to authenticated using (public.is_admin()) with check (public.is_admin());

create policy "admin_subscriptions_all" on public.subscriptions
for all to authenticated using (public.is_admin()) with check (public.is_admin());

create policy "admin_support_all" on public.support_tickets
for all to authenticated using (public.is_admin()) with check (public.is_admin());

create policy "admin_usage_all" on public.usage_events
for select to authenticated using (public.is_admin());

-- Conteúdo, tokens, testes e webhooks não possuem política pública.
-- Eles são acessados apenas pelo backend usando a chave secreta de serviço.

insert into public.plans (name, slug, description, price_cents, duration_days, features, active)
values
  ('Teste de 1 hora', 'teste-1h', 'Acesso de avaliação, limitado a uma utilização por conta.', 0, 0,
   '["Acesso por 60 minutos", "Catálogo de demonstração", "Suporte básico"]'::jsonb, true),
  ('Mensal', 'mensal', 'Assinatura individual por 30 dias.', 2990, 30,
   '["Conteúdo licenciado", "Até 2 dispositivos", "Qualidade adaptativa", "Suporte integrado"]'::jsonb, true),
  ('Trimestral', 'trimestral', 'Assinatura individual por 90 dias.', 7490, 90,
   '["Conteúdo licenciado", "Até 3 dispositivos", "Qualidade adaptativa", "Suporte prioritário"]'::jsonb, true),
  ('Anual', 'anual', 'Assinatura individual por 365 dias.', 23990, 365,
   '["Conteúdo licenciado", "Até 4 dispositivos", "Qualidade adaptativa", "Suporte prioritário"]'::jsonb, true)
on conflict (slug) do update set
  name = excluded.name,
  description = excluded.description,
  price_cents = excluded.price_cents,
  duration_days = excluded.duration_days,
  features = excluded.features,
  active = excluded.active;

insert into public.content_items (title, description, category, provider_asset_id, active)
values
  ('Canal demonstrativo', 'Substitua por uma fonte audiovisual sobre a qual você possua direitos de distribuição.', 'Demonstração', 'demo-channel', true),
  ('Conteúdo sob demanda', 'Item de exemplo para validar o controle de acesso.', 'Demonstração', 'demo-vod', true)
on conflict (provider_asset_id) do nothing;

-- Integração externa para geração de teste (Painel Slim ou outro provedor autorizado).
create table if not exists public.provider_trial_requests (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  phone text not null,
  email text,
  device text not null,
  phone_hash text not null,
  ip_hash text not null,
  status text not null default 'processing'
    check (status in ('processing','success','failed')),
  result_data jsonb,
  provider_response jsonb,
  error_message text,
  created_at timestamptz not null default now(),
  completed_at timestamptz
);

create index if not exists provider_trials_phone_created_idx
  on public.provider_trial_requests(phone_hash, created_at desc);
create index if not exists provider_trials_ip_created_idx
  on public.provider_trial_requests(ip_hash, created_at desc);
create index if not exists provider_trials_status_created_idx
  on public.provider_trial_requests(status, created_at desc);

alter table public.provider_trial_requests enable row level security;
drop policy if exists "provider_trials_admin_read" on public.provider_trial_requests;
create policy "provider_trials_admin_read"
  on public.provider_trial_requests for select
  to authenticated
  using (public.is_admin());

-- A função reserva o pedido antes de chamar o provedor e evita duas requisições
-- simultâneas para o mesmo WhatsApp.
create or replace function public.reserve_provider_trial(
  p_name text,
  p_phone text,
  p_email text,
  p_device text,
  p_phone_hash text,
  p_ip_hash text,
  p_cooldown_hours integer default 720,
  p_ip_cooldown_hours integer default 6
)
returns table(request_id uuid)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id uuid;
begin
  perform pg_advisory_xact_lock(hashtextextended(p_phone_hash, 0));

  if exists (
    select 1 from public.provider_trial_requests
    where phone_hash = p_phone_hash
      and status in ('processing','success')
      and created_at >= now() - make_interval(hours => greatest(p_cooldown_hours, 1))
  ) then
    raise exception 'trial_phone_cooldown';
  end if;

  if exists (
    select 1 from public.provider_trial_requests
    where ip_hash = p_ip_hash
      and status in ('processing','success')
      and created_at >= now() - make_interval(hours => greatest(p_ip_cooldown_hours, 1))
  ) then
    raise exception 'trial_ip_cooldown';
  end if;

  insert into public.provider_trial_requests(
    name, phone, email, device, phone_hash, ip_hash, status, created_at
  ) values (
    left(trim(p_name), 120),
    left(trim(p_phone), 20),
    nullif(left(trim(coalesce(p_email, '')), 180), ''),
    left(trim(p_device), 80),
    p_phone_hash,
    p_ip_hash,
    'processing',
    now()
  ) returning id into v_id;

  return query select v_id;
end;
$$;

revoke all on function public.reserve_provider_trial(text,text,text,text,text,text,integer,integer)
  from public, anon, authenticated;
grant execute on function public.reserve_provider_trial(text,text,text,text,text,text,integer,integer)
  to service_role;
